FROM python:3.11-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update && apt-get install -y gnupg2 wget git
RUN apt-get remove -y libze-intel-gpu1 libigc1 libigdfcl1 libze-dev || true; \
    apt-get update; \
    apt-get install -y curl
RUN curl -sL 'https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=get&search=0x0C0E6AF955CE463C03FC51574D098D70AFBE5E1F' | tee /etc/apt/trusted.gpg.d/driver.asc
RUN echo -e "Types: deb\nURIs: https://ppa.launchpadcontent.net/kobuk-team/intel-graphics/ubuntu/\nSuites: plucky\nComponents: main\nSigned-By: /etc/apt/trusted.gpg.d/driver.asc" > /etc/apt/sources.list.d/driver.sources
RUN apt-get update && apt-get install -y libze-intel-gpu1 libze1 intel-metrics-discovery intel-opencl-icd clinfo intel-gsc && apt-get install -y libze-intel-gpu1 libze1 intel-metrics-discovery intel-opencl-icd clinfo intel-gsc && apt-get install -y libze-dev intel-ocloc libze-intel-gpu-raytracing

RUN useradd -m -s /bin/bash user && \
    mkdir -p /home/user && \
    chown -R user /home/user/

RUN mkdir /templates && \
    chown -R user /templates
COPY ./edgecraftrag/prompt_template/default_prompt.txt /templates/
RUN chown -R user /templates/default_prompt.txt

COPY ./edgecraftrag /home/user/edgecraftrag

RUN mkdir -p /home/user/ui_cache
ENV UI_UPLOAD_PATH=/home/user/ui_cache

USER user

WORKDIR /home/user/edgecraftrag
RUN pip3 install --no-cache-dir --upgrade setuptools==70.0.0 --break-system-packages && \
    pip3 install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt --break-system-packages

RUN pip3 install --no-cache-dir docarray==0.40.0 --break-system-packages

WORKDIR /home/user/
RUN git clone https://github.com/openvinotoolkit/openvino.genai.git genai
ENV PYTHONPATH="$PYTHONPATH:/home/user/genai/tools/llm_bench"

RUN python3 -m nltk.downloader -d /home/user/nltk_data punkt_tab averaged_perceptron_tagger_eng

ENTRYPOINT ["python3", "-m", "edgecraftrag.server"]
