apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: edgecraftrag-server
spec:
  selector:
    matchLabels:
      app: edgecraftrag-server
  template:
    metadata:
      labels:
        app: edgecraftrag-server
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        supplementalGroups:
        - {{ .Values.gpu.groups.video }}
        - {{ .Values.gpu.groups.render }}
      containers:
        - name: edgecraftrag-server
          image: "{{ .Values.image.ecrag.registry }}/edgecraftrag-server:{{ .Values.image.ecrag.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: edgecraftrag-env
          env:
            - name: PIPELINE_SERVICE_HOST_IP
              value: "0.0.0.0"
          ports:
            - containerPort: {{ .Values.ports.pipeline }}
          volumeMounts:
            - name: model-path
              mountPath: /home/user/models
            - name: docs-path
              mountPath: /home/user/docs
            - name: tmpfile-path
              mountPath: /home/user/ui_cache
            - name: prompt-path
              mountPath: /templates/custom
            - name: dri-device
              mountPath: /dev/dri
      volumes:
        - name: model-path
          hostPath:
            path: "{{ .Values.paths.model }}"
        - name: docs-path
          hostPath:
            path: "{{ .Values.paths.docs }}"
        - name: tmpfile-path
          hostPath:
            path: "{{ .Values.paths.tmpfile }}"
        - name: prompt-path
          hostPath:
            path: "{{ .Values.paths.prompt }}"
        - name: dri-device
          hostPath:
            path: /dev/dri
