# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecrag
spec:
  replicas: {{ .Values.replica.ecrag }}
  selector:
    matchLabels:
      app: ecrag
  template:
    metadata:
      labels:
        app: ecrag
    spec:
      containers:
        - name: ecrag
          image: "{{ .Values.image.ecrag.registry }}/edgecraftrag:{{ .Values.image.ecrag.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: edgecraftrag-env
          ports:
            - containerPort: {{ .Values.ports.mega }}
          volumeMounts:
            - name: model-path
              mountPath: /home/user/models
            - name: docs-path
              mountPath: /home/user/docs
            - name: tmpfile-path
              mountPath: /home/user/ui_cache
            - name: prompt-path
              mountPath: /templates/custom
      volumes:
        - name: model-path
          hostPath:
            path: "{{ .Values.paths.model }}"
        - name: docs-path
          hostPath:
            path: "{{ .Values.paths.docs }}"
        - name: tmpfile-path
          hostPath:
            path: "{{ .Values.paths.tmpfile }}"
        - name: prompt-path
          hostPath:
            path: "{{ .Values.paths.prompt }}"
