apiVersion: v1
kind: Service
metadata:
  name: edgecraftrag-ui
spec:
  type: NodePort
  selector:
    app: edgecraftrag-ui
  ports:
    - protocol: TCP
      port: {{ .Values.ports.ui.port }}
      targetPort: {{ .Values.ports.ui.port }}
      nodePort: {{ .Values.ports.ui.nodePort }}
