import type { Language } from "../../routes/types.js";

export const languagesList: Language[] = [
	{ name: 'C' },
	{ name: 'C++' },
	{ name: 'C#' },
	{ name: 'Golang' },
	{ name: 'Java' },
	{ name: 'Python' },
	{ name: 'JavaScript' },
	{ name: 'Swift' },
	{ name: 'Ruby' },
	{ name: 'Go' },
	{ name: 'Rust' },
	{ name: 'PHP' },
	{ name: 'TypeScript' },
	{ name: 'Kotlin' },
	{ name: 'Objective-C' },
	{ name: 'Perl' },
	{ name: 'MATLAB' },
	{ name: 'R' },
	{ name: 'Lua' },
	{ name: 'Bash' },
	{ name: 'HTML' },
	{ name: 'CSS' },
	{ name: 'SQL' },
];