FROM python:3.11-slim

ENV LANG C.UTF-8

# Install system dependencies
RUN apt-get update \
    && apt-get install -y ffmpeg

COPY ./asr /asr
RUN pip install -r /asr/requirements.txt

WORKDIR /asr

ENTRYPOINT ["python", "asr_server.py"]

