FROM ubuntu:22.04

RUN apt-get -qq update

WORKDIR /home/ubuntu

COPY launch_workflow_service.sh requirements.txt main.py workflow.py ./

RUN chmod +x ./launch_workflow_service.sh

CMD ["./launch_workflow_service.sh"]
