# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

image:
  ecrag:
    registry: opea
    tag: latest
  vllm:
    registry: intel
    tag: 1.1-preview

replica:
  ecrag: 1
  ecrag_ui: 1

env:
  no_proxy: ""
  http_proxy: ""
  https_proxy: ""
  HOST_IP: ""
  ENABLE_BENCHMARK: false
  CHAT_HISTORY_ROUND: 0
  METADATA_DATABASE_URL: ""

llm:
  LLM_MODEL: ""
  DTYPE: float16
  ZE_AFFINITY_MASK: 0,1
  ENFORCE_EAGER: 1
  TRUST_REMOTE_CODE: 1
  DISABLE_SLIDING_WINDOW: 1
  GPU_MEMORY_UTIL: 0.9
  NO_ENABLE_PREFIX_CACHING: 1
  MAX_NUM_BATCHED_TOKENS: 8192
  MAX_MODEL_LEN: 49152
  DISABLE_LOG_REQUESTS: 1
  BLOCK_SIZE: 64
  QUANTIZATION: sym_int4
  TP: 1
  DP: 1


ports:
  pipeline: 16010
  mega: 16011
  ui:
    port: 8082
    nodePort: 30082
  vllm: 8086

paths:
  model: /home/user/models
  docs: /home/user/docs
  tmpfile: /home/user/ui_cache
  prompt: /templates/custom

gpu:
  groups:
    video: 44
    render: 991
