# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Use node 20.11.1 as the base image
FROM node:20.11.1 as vite-app
 
COPY ./react /usr/app/react
WORKDIR /usr/app/react


RUN ["npm", "install"]
RUN ["npm", "run", "build"]


FROM nginx:alpine

COPY --from=vite-app /usr/app/react/dist /usr/share/nginx/html

COPY ./react/nginx.conf /tmp/nginx.conf
ENTRYPOINT envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && /usr/sbin/nginx -g "daemon off;"
