# Copyright (C) 2025 Huawei Technologies Co., Ltd.
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REPO=opea
ARG BASE_TAG=latest
FROM $IMAGE_REPO/comps-base:$BASE_TAG-openeuler

USER root
# FFmpeg needed for media processing
RUN yum update -y && \
    yum install -y ffmpeg && \
    yum clean all && rm -rf /var/cache/yum
USER user

COPY ./docsum.py $HOME/docsum.py

ENTRYPOINT ["python", "docsum.py"]
