FROM ubuntu:latest as builder

RUN apt-get update && apt-get install -y \
    build-essential \
    autoconf \
    git
WORKDIR /workspace
RUN git clone https://github.com/vllm-project/vllm.git && cd vllm && git checkout v0.6.6

FROM rocm/vllm:rocm6.3.1_mi300_ubuntu22.04_py3.12_vllm_0.6.6

# Set the working directory
WORKDIR /workspace

# Copy the entrypoints files into the image
COPY --from=builder /workspace/vllm/vllm/entrypoints/openai /workspace

# Expose the port used by the API server
EXPOSE 8011

# Set environment variables
ENV HUGGINGFACE_HUB_CACHE=/workspace
ENV VLLM_USE_TRITON_FLASH_ATTENTION=0
ENV PYTORCH_JIT=0

# Set the entrypoint to the api_server.py script
ENTRYPOINT ["python3", "/workspace/api_server.py"]
