# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

#FROM vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest
FROM vault.habana.ai/gaudi-docker/1.16.2/ubuntu22.04/habanalabs/pytorch-installer-2.2.2:latest

RUN git clone https://github.com/HabanaAI/vllm-fork.git /workspace/vllm 

# COPY ./ /workspace/vllm

WORKDIR /workspace/vllm

RUN pip install --no-cache-dir -v -r requirements-hpu.txt

ENV PT_HPU_ENABLE_LAZY_COLLECTIVES=true

RUN VLLM_TARGET_DEVICE=hpu python3 setup.py install

WORKDIR /workspace/

RUN ln -s /workspace/vllm/tests && ln -s /workspace/vllm/examples && ln -s /workspace/vllm/benchmarks

CMD ["/bin/bash"]
