FROM python:3.9-slim

ENV LANG C.UTF-8
ENV PYTHONPATH=/home/user:/GPT-SoVITS/GPT_SoVITS

# Install system dependencies
RUN apt-get update \
    && apt-get install -y ffmpeg \
    && apt-get install -y build-essential wget numactl git \
    && apt-get install -y libomp-dev google-perftools

ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libiomp5.so:/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4
ENV MALLOC_CONF="oversize_threshold:1,background_thread:true,metadata_thp:auto,dirty_decay_ms:9000000000,muzzy_decay_ms:9000000000"
ENV OMP_NUM_THREADS=56
    

RUN git clone https://github.com/RVC-Boss/GPT-SoVITS.git /GPT-SoVITS -b main

RUN pip install -r /GPT-SoVITS/requirements.txt

COPY ./tts/tts_server.py /GPT-SoVITS/
COPY ./tts/config.py /GPT-SoVITS/

# Download the sample ref wav
RUN wget https://github.com/intel/intel-extension-for-transformers/raw/main/intel_extension_for_transformers/neural_chat/assets/audio/sample.wav -P /GPT-SoVITS
RUN wget https://github.com/intel/intel-extension-for-transformers/raw/main/intel_extension_for_transformers/neural_chat/assets/audio/welcome_cn.wav -P /GPT-SoVITS


#RUN useradd -m -s /bin/bash user && \
#    mkdir -p /home/user && \
#    chown -R user /home/user/

#USER user

WORKDIR /GPT-SoVITS

ENTRYPOINT ["python", "tts_server.py"]
