#!/usr/bin/env bash

# Copyright (C) 2025 Advanced Micro Devices, Inc.

export HOST_IP=${ip_address}
export EXTERNAL_HOST_IP=${ip_address}

export SEARCH_EMBEDDING_MODEL_ID='BAAI/bge-base-en-v1.5'
export SEARCH_GOOGLE_API_KEY=${GOOGLE_API_KEY}
export SEARCH_GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
export SEARCH_HUGGINGFACEHUB_API_TOKEN=${HF_TOKEN}
export SEARCH_LLM_MODEL_ID='Intel/neural-chat-7b-v3-3'
export SEARCH_RERANK_MODEL_ID='BAAI/bge-reranker-base'

export MODEL_CACHE="./data"

export SEARCH_BACKEND_SERVICE_PORT=3008
export SEARCH_EMBEDDING_SERVICE_PORT=3002
export SEARCH_FRONTEND_SERVICE_PORT=5173
export SEARCH_LLM_SERVICE_PORT=3007
export SEARCH_RERANK_SERVICE_PORT=3005
export SEARCH_TEI_EMBEDDING_PORT=3001
export SEARCH_TEI_RERANKING_PORT=3004
export SEARCH_VLLM_SERVICE_PORT=3080
export SEARCH_WEB_RETRIEVER_SERVICE_PORT=3003

export SEARCH_BACKEND_SERVICE_ENDPOINT=http://${EXTERNAL_HOST_IP}:${SEARCH_BACKEND_SERVICE_PORT}/v1/searchqna
export SEARCH_EMBEDDING_SERVICE_HOST_IP=${HOST_IP}
export SEARCH_LLM_ENDPOINT=http://${HOST_IP}:${SEARCH_VLLM_SERVICE_PORT}
export SEARCH_LLM_SERVICE_HOST_IP=${HOST_IP}
export SEARCH_MEGA_SERVICE_HOST_IP=${HOST_IP}
export SEARCH_RERANK_SERVICE_HOST_IP=${HOST_IP}
export SEARCH_TEI_EMBEDDING_ENDPOINT=http://${HOST_IP}:${SEARCH_TEI_EMBEDDING_PORT}
export SEARCH_TEI_RERANKING_ENDPOINT=http://${HOST_IP}:${SEARCH_TEI_RERANKING_PORT}
export SEARCH_WEB_RETRIEVER_SERVICE_HOST_IP=${HOST_IP}
