# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# FROM vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest
FROM vault.habana.ai/gaudi-docker/1.16.0/ubuntu22.04/habanalabs/pytorch-installer-2.2.2:latest

ENV LANG=en_US.UTF-8

WORKDIR /root/ray_serve

# copy the source code to the package directory
COPY comps/llms/text-generation/ray_serve/ /root/ray_serve

RUN pip install -r /root/ray_serve/docker/requirements.txt && \
    pip install --upgrade-strategy eager optimum[habana]

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    service ssh restart

ENV no_proxy=localhost,127.0.0.1
ENV PYTHONPATH=$PYTHONPATH:/root:/root/ray_serve

# Required by DeepSpeed
ENV RAY_EXPERIMENTAL_NOSET_HABANA_VISIBLE_MODULES=1

ENV PT_HPU_LAZY_ACC_PAR_MODE=0

ENV PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES=0

ENV PT_HPU_ENABLE_WEIGHT_CPU_PERMUTE=0

ENV PT_HPU_ENABLE_LAZY_COLLECTIVES=true