apiVersion: v1
kind: Service
metadata:
  name: edgecraftrag-server
spec:
  selector:
    app: edgecraftrag-server
  ports:
    - protocol: TCP
      port: {{ .Values.ports.pipeline }}
      targetPort: {{ .Values.ports.pipeline }}
