apiVersion: v1
kind: Service
metadata:
  name: llm-serving-xpu
spec:
  selector:
    app: llm-serving-xpu
  ports:
    - protocol: TCP
      port: {{ .Values.ports.vllm }}
      targetPort: {{ .Values.ports.vllm }}
