{
 "title": "Text Embedding Inference",
 "description": "Monitor TEI services on kubernetes",
 "time": { "from": "now-1h", "to": "now-1m" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(te_request_count,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(te_request_count{namespace=\"\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(te_embed_success{namespace=\"\", job=\"$job\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(te_embed_count{namespace=\"\", job=\"$job\"}[1m]))",
     "legendFormat": "Total Count"
    }
   ]
  },
  {
   "title": "Queue Duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_embed_queue_duration_bucket{namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_embed_queue_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_embed_queue_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(te_request_duration_bucket{namespace=\"\", job=\"$job\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Number of replicas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(te_request_count{namespace=\"\", job=\"$job\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(te_queue_size{namespace=\"\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_embed_duration_bucket{namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_embed_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_embed_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Tokenization Duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_tokenization_duration_bucket{namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_tokenization_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_tokenization_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Inference quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_inference_duration_bucket{namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_inference_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_inference_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Tokenization Latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_embed_tokenization_duration_bucket{namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_embed_tokenization_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_embed_tokenization_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Batching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg(te_batch_next_size_bucket{namespace=\"\", job=\"$job\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Queue quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_queue_duration_bucket{namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_queue_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_queue_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Input Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 29 },
   "targets": [
    {
     "expr": "avg(te_request_input_length_bucket{namespace=\"\", job=\"$job\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Embed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Embed Inference Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_embed_inference_duration_bucket{method=\"\", namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_embed_inference_duration_bucket{method=\"\", namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_embed_inference_duration_bucket{method=\"\", namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Embed Inference Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(te_embed_inference_duration_bucket{method=\"\", namespace=\"\", job=\"$job\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Inference Duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_embed_inference_duration_bucket{namespace=\"\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_embed_inference_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_embed_inference_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } }
 ]
}