{
 "title": "Text Generation Inference",
 "time": { "from": "now-30m", "to": "now-30s" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(tgi_request_count, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Time to first token",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$B + $C", "type": "math" }
   ]
  },
  {
   "title": "Decode per-token latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.5, sum by (le) (rate(tgi_batch_forward_duration_bucket{method=\"decode\", job=\"$job\"}[10m]))) * 1000)>0"
    }
   ]
  },
  {
   "title": "Throughput (generated tok/s)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((rate(tgi_request_generated_tokens_sum{job=\"$job\"}[10m]) / rate(tgi_request_generated_tokens_count{job=\"$job\"}[10m]))>0)"
    }
   ]
  },
  {
   "title": "Number of tokens per prompt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_input_length_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_input_length_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_input_length_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Number of generated tokens per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_generated_tokens_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_generated_tokens_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_generated_tokens_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(tgi_request_success{job=\"$job\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(tgi_request_failure{job=\"$job\"}[1m])) by (err)",
     "legendFormat": "Error: {{err}}"
    }
   ]
  },
  {
   "title": "Mean Time Per Token quantiles",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_mean_time_per_token_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_mean_time_per_token_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_mean_time_per_token_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Mean Time Per Token",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(tgi_request_mean_time_per_token_duration_bucket{job=\"$job\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Number of replicas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count(tgi_request_count{job=\"$job\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tgi_queue_size{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Batching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Max tokens per batch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg(tgi_batch_current_max_tokens{job=\"$job\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Speculated Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_skipped_tokens_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_skipped_tokens_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_skipped_tokens_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_input_length_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_input_length_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_input_length_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "avg(tgi_batch_current_size{job=\"$job\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Concatenates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_concat{job=\"$job\"}[1m])) by (reason)",
     "legendFormat": "Reason: {{ reason }}"
    }
   ]
  },
  {
   "title": "Queue quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_queue_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_queue_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_queue_duration_bucket{job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Prefill", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Prefill Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"prefill\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"prefill\", job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"prefill\", job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Prefill Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_inference_duration_bucket{method=\"prefill\", job=\"$job\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Decode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Decode quantiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Decode Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_inference_duration_bucket{method=\"decode\", job=\"$job\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Forward quantiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_forward_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_forward_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_forward_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Forward Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_forward_duration_bucket{method=\"decode\", job=\"$job\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Token Decode quantiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_decode_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_decode_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_decode_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Token Decode Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_decode_duration_bucket{method=\"decode\", job=\"$job\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Filter Batch quantiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_filter_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_filter_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_filter_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Filter Batch Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 84 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_filter_duration_bucket{method=\"decode\", job=\"$job\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Batch Concat quantiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_concat_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_concat_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_concat_duration_bucket{method=\"decode\", job=\"$job\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Batch Concat latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 84 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_concat_duration_bucket{method=\"decode\", job=\"$job\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}