#!/usr/bin/env bash

# Copyright (C) 2025 Zensar Technologies Private Ltd.
# SPDX-License-Identifier: Apache-2.0

export HOST_IP=${ip_address}
export HF_TOKEN=${HF_TOKEN}
export ARB_POSTHEARING_ASSISTANT_MAX_INPUT_TOKENS=2048
export ARB_POSTHEARING_ASSISTANT_MAX_TOTAL_TOKENS=4096
export ARB_POSTHEARING_ASSISTANT_LLM_MODEL_ID="mistralai/Mistral-7B-Instruct-v0.2"
export ARB_POSTHEARING_ASSISTANT_VLLM_SERVICE_PORT="8008"
export ARB_POSTHEARING_ASSISTANT_LLM_ENDPOINT="http://${HOST_IP}:${ARB_POSTHEARING_ASSISTANT_VLLM_SERVICE_PORT}"
export ARB_POSTHEARING_ASSISTANT_LLM_SERVER_PORT="9000"
export ARB_POSTHEARING_ASSISTANT_BACKEND_SERVER_PORT="18072"
export ARB_POSTHEARING_ASSISTANT_FRONTEND_PORT="18073"
export BACKEND_SERVICE_ENDPOINT="http://${HOST_IP}:${ARB_POSTHEARING_ASSISTANT_BACKEND_SERVER_PORT}/v1/arb-post-hearing"
