{
 "title": "Gaudi HPU Metrics",
 "description": "Gaudi HPU Metrics based on the Prometheus metrics from https://docs.habana.ai/en/latest/Orchestration/Prometheus_Metric_Exporter.html",
 "tags": [
  "prometheus",
  "Gaudi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(habanalabs_kube_info,instance)"
    }
   },
   {
    "name": "hpu",
    "label": "HPU",
    "query": {
     "query": "label_values(habanalabs_device_config{instance=\"$node\"},UUID)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Driver Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "habanalabs_device_config{instance=\"$node\", UUID=\"$hpu\"}",
     "legendFormat": "{{driver_version}}"
    }
   ]
  },
  {
   "title": "HPU Utilization %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "habanalabs_utilization{instance=\"$node\", UUID=\"$hpu\"}/100",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "HPU Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "habanalabs_power_mW{instance=\"$node\", UUID=\"$hpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "PCIe Throughput",
   "type": "timeseries",
   "description": "PCIe Throughput.",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "habanalabs_pcie_receive_throughput{UUID=\"$hpu\", instance=\"$node\"}",
     "legendFormat": "{{uuid}}"
    },
    {
     "expr": "habanalabs_pcie_transmit_throughput{UUID=\"$hpu\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onchip Temperature",
   "type": "gauge",
   "description": "onchip temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "habanalabs_temperature_onchip{UUID=\"$hpu\", instance=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Onboard Temperature",
   "type": "gauge",
   "description": "onboard temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "habanalabs_temperature_onboard{UUID=\"$hpu\", instance=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Bios Version",
   "type": "stat",
   "description": "The BIOS of the hpu board.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "habanalabs_device_config{instance=\"$node\", UUID=\"$hpu\"}",
     "legendFormat": "{{vbios_version}}"
    }
   ]
  },
  {
   "title": "Firmware Version",
   "type": "stat",
   "description": "The Firmware of the HPU board.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "habanalabs_device_config{instance=\"$node\", UUID=\"$hpu\"}",
     "legendFormat": "{{vbios_version}}"
    }
   ]
  },
  {
   "title": "HPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "habanalabs_utilization{instance=\"$node\", UUID=\"$hpu\"}/100"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Core hpu temperature. in degrees C.",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "habanalabs_temperature_onboard{UUID=\"$hpu\", instance=\"$node\"}",
     "legendFormat": "{{uuid}}"
    },
    {
     "expr": "habanalabs_temperature_onchip{UUID=\"$hpu\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HPU Clock SOC Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "habanalabs_clock_soc_mhz{UUID=\"$hpu\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "habanalabs_memory_used_bytes{UUID=\"$hpu\", instance=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "HPU power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "habanalabs_power_mW{instance=\"$node\", UUID=\"$hpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "habanalabs_memory_used_bytes{UUID=\"$hpu\", instance=\"$node\"} / habanalabs_memory_total_bytes{UUID=\"$hpu\", instance=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}