FROM rocm/vllm:rocm6.2_mi300_ubuntu20.04_py3.9_vllm_0.6.4

# Set the working directory
WORKDIR /workspace

# Copy the api_server.py into the image
ADD https://raw.githubusercontent.com/vllm-project/vllm/refs/tags/v0.7.0/vllm/entrypoints/openai/api_server.py /workspace/api_server.py

# Expose the port used by the API server
EXPOSE 8011

# Set environment variables
ENV HUGGINGFACE_HUB_CACHE=/workspace
ENV WILM_USE_TRITON_FLASH_ATTENTION=0
ENV PYTORCH_JIT=0

# Set the entrypoint to the api_server.py script
ENTRYPOINT ["python3", "/workspace/api_server.py"]
